---
version: '3'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9050:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      - AspNetCoreReactWebApp_net
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - AspNetCoreReactWebApp_net
  
  pgadmin:
    image: dpage/pgadmin4:5.4
    container_name: pgadmin
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_PORT: 80
    volumes:
      - "../volumes/pgadmin:/var/lib/pgadmin4/storage"
    networks:
      - AspNetCoreReactWebApp_net

networks:
  AspNetCoreReactWebApp_net:
    driver: bridge

volumes:
  portainer_data: